# Quick Access

The data from the `recount3` project is accessible through R/Bioconductor packages as well as raw files. You can access the data through:

* `r BiocStyle::Biocpkg("recount3")`: this R/Bioconductor package retrieves the data from the [IDIES](https://idies.jhu.edu/) servers and builds `RangedSummarizedExperiment` objects by study that can be used with many Bioconductor analysis packages for downstream analyses (DOI: [10.1038/nmeth.3252](https://doi.org/10.1038/nmeth.3252)).
* `r BiocStyle::Biocpkg("snapcount")`: this R/Bioconductor package also provides access to data from `recount2` and `recount3` through a query-based interface. 
* _raw files_: these are text files that are hosted by IDIES and can be used with other programming software outside of R.

## Quick recount3

If you want to access the data `r BiocStyle::Biocpkg("recount3")`, here's some R code that you can use. See the [Bioconductor chapter](#bioconductor) for the full output of these commands and more details.

```{r 'recount3_code', eval = FALSE}
## Install the recount3 R/Bioconductor package
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("recount3")

## Load recount3 R package
library("recount3")

## Find all available human projects
human_projects <- available_projects()

## Find the project you are interested in,
## here we use SRP009615 as an example
proj_info <- subset(
    human_projects,
    project == "SRP009615" & project_type == "data_sources"
)

## Create a RangedSummarizedExperiment (RSE) object at the gene level
rse_gene_SRP009615 <- create_rse(proj_info)

## Explore that RSE object
rse_gene_SRP009615
```

## Quick snapcount

TODO

## Quick raw files

The raw `recount3` files are hosted by [IDIES](https://idies.jhu.edu/) and are publicly available. We separated every piece of information into its own file. These files can be accessed without using R through your own favorite programming solution. For example, the files for human study `SRP009615` annotated with GENCODE v26 are:

Metadata files:

1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/metadata/15/SRP009615/sra.sra.SRP009615.MD.gz
1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/metadata/15/SRP009615/sra.recount_project.SRP009615.MD.gz
1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/metadata/15/SRP009615/sra.recount_qc.SRP009615.MD.gz
1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/metadata/15/SRP009615/sra.recount_seq_qc.SRP009615.MD.gz
1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/metadata/15/SRP009615/sra.recount_pred.SRP009615.MD.gz

Gene files:

1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/gene_sums/15/SRP009615/sra.gene_sums.SRP009615.G026.gz

Annotation files:

1. http://idies.jhu.edu/recount3/data/human/annotations/gene_sums/human.gene_sums.G026.gtf.gz


If you are interested in exploring what are the available projects in `recount3`, you might be interested in accessing:

1. http://idies.jhu.edu/recount3/data/human/data_sources/sra/metadata/sra.recount_project.MD.gz
1. http://idies.jhu.edu/recount3/data/human/data_sources/gtex/metadata/gtex.recount_project.MD.gz
1. http://idies.jhu.edu/recount3/data/human/data_sources/tcga/metadata/tcga.recount_project.MD.gz

For more details about the structure of these files, check the [Raw Files chapter](#raw-files).

